
public class login extends javax.swing.JFrame {

   Bank b ;
   int st ;
    public login() {
        st=0;
        initComponents();
        e_acc_no.setVisible(false);
        jacc.setVisible(false);
        jbalance.setVisible(false);
        e_b.setVisible(false);
        Proceed.setVisible(false);
        b=new Bank();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_account = new javax.swing.JButton();
        e_acc_no = new javax.swing.JTextField();
        e_b = new javax.swing.JTextField();
        jacc = new javax.swing.JLabel();
        jbalance = new javax.swing.JLabel();
        war = new java.awt.Label();
        mod_bal = new javax.swing.JButton();
        tot_bal = new java.awt.Button();
        tar1 = new java.awt.TextArea();
        min_max = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Proceed = new javax.swing.JButton();
        get_acc = new javax.swing.JButton();
        count_bal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Add_account.setText("Add account");
        Add_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_accountActionPerformed(evt);
            }
        });

        e_acc_no.setText("0");

        e_b.setText("0.0");

        jacc.setText("Enter Acc no");

        jbalance.setText("Enter balance");

        mod_bal.setText("Modify Balance");
        mod_bal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_balActionPerformed(evt);
            }
        });

        tot_bal.setLabel("Total Balance");
        tot_bal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tot_balActionPerformed(evt);
            }
        });

        min_max.setText("Min and Max Balance");
        min_max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min_maxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel4.setText("XYZ  BANK");

        Proceed.setText("Proceed");
        Proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedActionPerformed(evt);
            }
        });

        get_acc.setText("Get Account Info");
        get_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_accActionPerformed(evt);
            }
        });

        count_bal.setText("Count Sp_balance");
        count_bal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_balActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Add_account, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mod_bal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(get_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(min_max)
                        .addGap(21, 21, 21)
                        .addComponent(tot_bal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(count_bal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tar1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(Proceed))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(e_acc_no, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jacc, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(e_b, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(war, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mod_bal)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Add_account)
                                .addComponent(min_max, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(get_acc)
                                .addComponent(tot_bal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(count_bal)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jacc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e_acc_no, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_b, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbalance))
                .addGap(18, 18, 18)
                .addComponent(Proceed)
                .addGap(31, 31, 31)
                .addComponent(war, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tar1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_accountActionPerformed
        st=1;
        
        e_acc_no.setVisible(true);
        jacc.setVisible(true);
        jbalance.setVisible(true);
        e_b.setVisible(true);
        Proceed.setVisible(true);
        Proceed.setText("Add");
              
    }//GEN-LAST:event_Add_accountActionPerformed

    private void mod_balActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_balActionPerformed
        st=2;
        e_b.setVisible(false);
        jbalance.setVisible(false);
        e_acc_no.setVisible(true);
        jacc.setVisible(true);
        Proceed.setVisible(true);
        Proceed.setText("Modify");
    }//GEN-LAST:event_mod_balActionPerformed

    private void tot_balActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tot_balActionPerformed
        
        e_acc_no.setVisible(false);
        jacc.setVisible(false);
        jbalance.setVisible(false);
        e_b.setVisible(false);
        Proceed.setVisible(false);
        tar1.append("\nTotal balance in bank: "+Bank.total_bal());
    }//GEN-LAST:event_tot_balActionPerformed

    private void min_maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min_maxActionPerformed
            
            e_acc_no.setVisible(false);
            jacc.setVisible(false);
            jbalance.setVisible(false);
            e_b.setVisible(false);
            Proceed.setVisible(false);
            double max,min;
            int n=Bank.arr.size();
            if(n>0)
            {
                max=min=Bank.arr.get(0).balance;
            
                for (int i = 1; i < n; i++)
                {
                    double temp=Bank.arr.get(i).balance;
                    if(temp < min)
                    {
                        min=temp;
                    }
                    if(temp > max)
                        max=temp;
                
                }
                tar1.append("\nMinimum balance is : "+min);
                tar1.append("\nMaximum balance is : "+max);
            }
            else {
                tar1.append("\nNo account is there in the bank");
            }
    }//GEN-LAST:event_min_maxActionPerformed

    private void ProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedActionPerformed
        if(st==1)
        {
            int acc_no;
            acc_no = Integer.parseInt( e_acc_no.getText());
            int n = Bank.arr.size();
            boolean  fl = false; 
            for(int i=0;i<n;i++)
            {
                if (acc_no == Bank.arr.get(i).acc_no)
                {
                    tar1.append("\nthis account number already exists !!");
                    fl=true;
                    break;
                }
            }
            double bal=Double.parseDouble(e_b.getText());
            if(fl==false)
            {
                Bank.Add_acc(acc_no,bal);
                tar1.append("\nAccount added successfully");
            }
                        
        }
        if(st==2)
        {
            int acc_no;
            acc_no = Integer.parseInt( e_acc_no.getText());
            
            int n = Bank.arr.size();
            boolean  fl = false; 
            for(int i=0;i<n;i++)
            {
                if (acc_no == Bank.arr.get(i).acc_no)
                {
                    BA ba=new BA(Bank.arr.get(i),this);
                    fl=true;
                    ba.setVisible(true);
                    this.setVisible(false);
                    break;
                }
            }
            if(fl==false)
            {
                tar1.append("\nAccount not found");
            }
            else 
            {
                
            }
                        
        }
        if(st==3)
        {
            double bal;
            int acc_no;
            acc_no = Integer.parseInt( e_acc_no.getText());
            int n = Bank.arr.size();
            boolean  fl = false; 
            for(int i=0;i<n;i++)
            {
                    if (acc_no == Bank.arr.get(i).acc_no)
                    {   
                    
                        bal = Bank.arr.get(i).balance;
                        tar1.append("\nAccount number = "+acc_no+"   Balance is = "+bal);
                        fl=true;
                        break;
                    }
            }
            if(fl==false)
            {
                tar1.append("\nAccount not found");
            }
        }
        if(st==4)
        {
            int count=0;
            double temp = Double.parseDouble(e_b.getText());
            int n=Bank.arr.size();
            if(n>0)
            {
                for (int i = 0; i < n; i++) {
                    if(Bank.arr.get(i).balance <= temp)
                    {
                        count++;
                    }
                }
                tar1.append("\nNumber of accounts having atleast "+temp+"Rs. balance is : "+count);   
            }
            else{
               tar1.append("\nNo account is there in the bank"); 
            }
        }    
        
        st=0;
        e_acc_no.setVisible(false);
        jacc.setVisible(false);
        jbalance.setVisible(false);
        e_b.setVisible(false);
        Proceed.setVisible(false);
            
    }//GEN-LAST:event_ProceedActionPerformed

    private void get_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_accActionPerformed
        st=3;
        jbalance.setVisible(false);
        e_b.setVisible(false);
        e_acc_no.setVisible(true);
        jacc.setVisible(true);
        Proceed.setVisible(true);
        Proceed.setText("Get info");
    }//GEN-LAST:event_get_accActionPerformed

    private void count_balActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_balActionPerformed
       st=4;
       e_acc_no.setVisible(false);
       jacc.setVisible(false);
       e_b.setVisible(true);
       jbalance.setVisible(true);
       Proceed.setVisible(true);
       Proceed.setText("Get info");
    }//GEN-LAST:event_count_balActionPerformed

    public static void main(String args[]) {
               
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_account;
    private javax.swing.JButton Proceed;
    private javax.swing.JButton count_bal;
    private javax.swing.JTextField e_acc_no;
    private javax.swing.JTextField e_b;
    private javax.swing.JButton get_acc;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jacc;
    private javax.swing.JLabel jbalance;
    private javax.swing.JButton min_max;
    private javax.swing.JButton mod_bal;
    private java.awt.TextArea tar1;
    private java.awt.Button tot_bal;
    private java.awt.Label war;
    // End of variables declaration//GEN-END:variables
}
